name: CML Deploy Iris API

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: zeta-yen-459809-k6
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker for GCR
      run: |
        gcloud auth configure-docker

    - name: Build & Push Docker Image
      run: |
        IMAGE_URI=gcr.io/zeta-yen-459809-k6/iris-api:latest
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI

    - name: Set GKE credentials
      run: |
        gcloud container clusters get-credentials iris-cluster --zone us-central1-a --project zeta-yen-459809-k6

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
